apiVersion: v2
name: provider-mock
description: Mock valet provider for testing
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - secrets
  - mock
  - operator
  - testing
maintainers:
  - name: lukasngl
