{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secret-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secret-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.azure.workloadIdentity.enabled }}
  {{- if .Values.azure.workloadIdentity.clientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId }}
  {{- end }}
  {{- end }}
{{- end }}
