{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "provider-azure.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider-azure.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "provider-azure.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "provider-azure.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
