{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "provider-azure.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider-azure.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.azure.workloadIdentity.enabled .Values.azure.workloadIdentity.clientId }}
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
