# permissions for end users to edit clientsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: client-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: clientsecret-editor-role
rules:
- apiGroups:
  - secret-manager.ngl.cx
  resources:
  - clientsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret-manager.ngl.cx
  resources:
  - clientsecrets/status
  verbs:
  - get
