# permissions for end users to view clientsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: client-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: clientsecret-viewer-role
rules:
- apiGroups:
  - secrets.my.domain
  resources:
  - clientsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.my.domain
  resources:
  - clientsecrets/status
  verbs:
  - get
