apiVersion: secrets.my.domain/v1beta1
kind: ClientSecret
metadata:
  labels:
    app.kubernetes.io/name: client-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: clientsecret-sample
spec:
  # TODO(user): Add fields here
